Change naming rule in lib files
e.g. __put -> __zplug::print::print::put (prefix::dir::file::func_name)

diff --git a/autoload/utils/__self__ b/autoload/utils/__self__
--- a/autoload/utils/__self__
+++ b/autoload/utils/__self__
@@ -6,12 +6,12 @@ __import "print/print"
 local main
 main="b4b4r07/zplug"
 
-__put "$fg_bold[default] * zplug self management$reset_color\n"
+__zplug::print::print::put "$fg_bold[default] * zplug self management$reset_color\n"
 
 if __check__ "$main"; then
     __update__ "$main"
 else
-    if ! __zpluged "$main"; then
+    if ! __zplug::core::core::zpluged "$main"; then
         __add__ "$main"
     fi
     __install__ "$main"
@@ -22,9 +22,9 @@ ln -snf \
     "$ZPLUG_HOME/init.zsh"
 
 if (( $status == 0)) && [[ -d $ZPLUG_HOME/repos/$main ]]; then
-    __put "$fg[green]Everything is ready. "
-    __put "$fg_bold[default]($ZPLUG_HOME/zplug)$reset_color\n"
+    __zplug::print::print::put "$fg[green]Everything is ready. "
+    __zplug::print::print::put "$fg_bold[default]($ZPLUG_HOME/zplug)$reset_color\n"
 else
-    __die "$fg[red]Error occured (see ${(%):-"%U"}$_ZPLUG_URL${(%):-"%u"})$reset_color\n"
+    __zplug::print::print::die "$fg[red]Error occured (see ${(%):-"%U"}$_ZPLUG_URL${(%):-"%u"})$reset_color\n"
     return 1
 fi
