:tada: v0.1.0
- Implement self update (close #1)
- Modify function prefix (zplug:: -> __zplug::)
- Fix many bugs :bug:
- Support updating binaries (gh-r specifier)
- Add header logo, license and usage
- Refactoring

diff --git a/zplug b/zplug
--- a/zplug
+++ b/zplug
@@ -1,9 +1,84 @@
-#!/bin/zsh
+#              _             
+#    _____ __ | |_   _  __ _ 
+#   |_  / '_ \| | | | |/ _` |
+#    / /| |_) | | |_| | (_| |
+#   /___| .__/|_|\__,_|\__, |
+#       |_|            |___/ 
+#
+#  zplug: zsh plugin manager
+# ===========================
+#
+# Download zplug and put it in ~/.zplug
+#
+#   curl -fLo ~/.zplug/zplug --create-dirs \
+#     https://raw.githubusercontent.com/b4b4r07/zplug/master/zplug
+#
+# Edit your .zshrc
+#
+#   source ~/.zplug/zplug
+#
+#   # Make sure you use double quotes
+#   zplug "zsh-users/zsh-syntax-highlighting"
+#   zplug "zsh-users/zsh-substring-search"
+#
+#   # shell commands
+#   zplug "holman/spark", as:cmd
+#   # shell commands (specify export directory path using `of` specifier)
+#   zplug "b4b4r07/http_code", as:cmd, of:bin
+#   # shell commands (whatever language is OK; e.g., perl script)
+#   zplug "k4rthik/git-cal", as:cmd
+#
+#   # binaries (from GitHub Releases)
+#   zplug "junegunn/fzf-bin", \
+#       as:cmd, \
+#       from:gh-r, \
+#       file:fzf
+#
+#   # branch/tag
+#   zplug "b4b4r07/enhancd", at:v1
+#
+#   # true or false
+#   zplug "hchbaw/opp.zsh", if:"[ ${ZSH_VERSION%%.*} -lt 5 ]"
+#
+#   # Group dependencies, emoji-cli depends on jq
+#   zplug "stedolan/jq", \
+#       as:bin, \
+#       file:jq, \
+#       from:gh-r \
+#       | zplug "b4b4r07/emoji-cli"
+#
+#   # source plugins and add commands to $PATH
+#   zplug load
+#
+# Then reload .zshrc and `zplug install; zplug load` to install plugins.
+# Visit https://github.com/b4b4r07/zplug for more information.
+#
+# The MIT License (MIT)
+# Copyright © 2015 Masaki Ishiyama <b4b4r07@gmail.com>
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the “Software”), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice shall be included in
+# all copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+# THE SOFTWARE.
 
 # environment variable (read-only)
 typeset -gx ZPLUG_NAME=zplug
 typeset -gx ZPLUG_VERSION=0.0.1
 typeset -gx ZPLUG_RAWURL="https://raw.githubusercontent.com/b4b4r07/zplug/master/zplug"
+typeset -gx ZPLUG_URL="https://github.com/b4b4r07/zplug"
 
 # set default value if not present
 typeset -gx ZPLUG_HOME=${ZPLUG_HOME:-~/zplug/repos}
@@ -34,7 +109,7 @@ bg_rotation_bar() {
     done
 }
 
-zplug::list()
+__zplug::list()
 {
     local v
     local -A B
@@ -42,24 +117,30 @@ zplug::list()
         B+=("${(@kv)zplugs[(eR)$v]}")
     done
     command printf '%-20s  =>  %s\n' "${(@kv)B}" \
+        | sed -e 's/-EMP-/""/g' \
         | perl -pe 's/^(.*)( *=>.*)$/\033[32m$1\033[m$2/g' \
-        | perl -pe 's/(as|of|from|to|if|dir|file|at|do)(:)/\033[34m$1\033[m$2/g'
+        | perl -pe 's/(as|of|from|to|if|dir|file|at|do|frozen)(:)/\033[34m$1\033[m$2/g'
 }
 
-zplug::update()
+__zplug::selfupdate()
+{
+    curl -fLo $ZPLUG_HOME/zplug --create-dirs $ZPLUG_RAWURL >/dev/null 2>&1
+    if [[ $status -eq 0 ]]; then
+        printf "\033[32mUpdated $ZPLUG_NAME ($ZPLUG_HOME/zplug)\033[m\n"
+    else
+        printf "\033[31mError occured (see $ZPLUG_URL)\033[m\n"
+        return 1
+    fi
+}
+
+__zplug::update()
 {
     # Process argments
-    local is_self
     case "$1" in
         --self)
-            is_self=1
+            __zplug::selfupdate; return $status
             ;;
     esac
-    shift
-
-    if [[ $is_self -eq 1 ]]; then
-        return
-    fi
 
     local cnt line
     cnt=0
@@ -70,8 +151,7 @@ zplug::update()
             # All variables are treated as local variable
             # because of background job (subprocess)
             local -A zspec
-            # zspec=( $(zplug::parser "$line") )
-            zspec=( ${(@f)"$(zplug::parser "$line")"} )
+            zspec=( ${(@f)"$(__zplug::parser "$line")"} )
             for k in ${(k)zspec}
             do
                 if [[ $zspec[$k] == "-EMP-" ]]; then
@@ -83,21 +163,37 @@ zplug::update()
             typeset -F SECONDS=0
 
             if [[ $zspec[frozen] -eq 1 ]]; then
-                command printf "\033[34mFrozen\033[m       $line\n"
+                command printf " \033[34m* Frozen\033[m    $line\n"
                 continue
             fi
 
             command printf "Updating...  $line\n"
-            (){
-                cd $zspec[dir]   || return 1
-                git pull --quiet || return 1
-            } 2>/dev/null
+            bg_rotation_bar & bg_pid=$!
+            () {
+                cd $zspec[dir] || cd ${zspec[dir]%/*} || return 2
+                if [[ $zspec[from] == "gh-r" ]]; then
+                    eval 'L=$zspec[name] bash -c "$(curl -L git.io/releases)" -s os'
+                else
+                    git pull --quiet
+                fi || return 1
+            } >/dev/null 2>&1
+            ret=$status
 
-            if [[ $status -eq 0 ]]; then
-                command printf "\033[32mUpdated!\033[m     %-20s\t(%.2fs)\n" "$line" $SECONDS
-            else
-                command printf "\033[31mNot Updated\033[m  %-20s\t(%.2fs)\n" "$line" $SECONDS
-            fi
+            # Kill bg_rotation_bar animation
+            kill -9 $bg_pid
+
+            case $ret in
+                0)
+                    command printf "\033[32mUpdated!\033[m     %-20s\t(%.2fs)\n" "$line" $SECONDS
+                    ;;
+                1)
+                    command printf "\033[31mNot Updated\033[m  %-20s\t(%.2fs)\n" "$line" $SECONDS
+                    ;;
+                2)
+                    sleep 1
+                    command printf "\033[35mNot Found\033[m    %-20s\t(%.2fs)\n" "$line" $((SECONDS-1))
+                    ;;
+            esac
         } &
         # Prevent having too many subprocesses
         (( (cnt += 1) % ZPLUG_THREAD == 0 )) && wait
@@ -105,7 +201,7 @@ zplug::update()
     wait
 }
 
-zplug::install()
+__zplug::install()
 {
     local cnt line fail job
     local start end
@@ -127,8 +223,7 @@ zplug::install()
             # All variables are treated as local variable
             # because of background job (subprocess)
             local -A zspec
-            # zspec=( $(zplug::parser "$line") )
-            zspec=( ${(@f)"$(zplug::parser "$line")"} )
+            zspec=( ${(@f)"$(__zplug::parser "$line")"} )
             for k in ${(k)zspec}
             do
                 if [[ $zspec[$k] == "-EMP-" ]]; then
@@ -158,7 +253,7 @@ zplug::install()
                     --depth=1 \
                     --recursive \
                     --quiet \
-                    -b $zspec[at] \
+                    --branch $zspec[at] \
                     git@github.com:"$line" "$line" >/dev/null 2>&1
                 ret=$status
             fi
@@ -214,7 +309,7 @@ zplug::install()
     command printf "$ZPLUG_NAME: total time %d sec\n" $(($end - $start))
 }
 
-zplug::parser()
+__zplug::parser()
 {
     local zplug split_array
     zplug="$1"
@@ -227,7 +322,7 @@ zplug::parser()
     # If value is empty, set -EMP- value to it
     local name as of to from if dir file at do frozen
     name="${split_array[1]}"
-    as=${${${(M)split_array:#as*}#*:}:--EMP-}
+    as=${${${(M)split_array:#as*}#*:}:-src}
     of=${${${(M)split_array:#of*}#*:}:--EMP-}
     to=${${${(M)split_array:#to*}#*:}:--EMP-}
     from=${${${(M)split_array:#from*}#*:}:--EMP-}
@@ -261,7 +356,7 @@ zplug::parser()
     done
 }
 
-zplug::load()
+__zplug::load()
 {
     local f files k
     local zplug
@@ -270,7 +365,7 @@ zplug::load()
     for zplug in ${(k)zplugs}
     do
         # Set zspec
-        zspec=( ${(@f)"$(zplug::parser "$zplug")"} )
+        zspec=( ${(@f)"$(__zplug::parser "$zplug")"} )
         # Replace -EMP- with ""(empty)
         for k in ${(k)zspec}
         do
@@ -290,7 +385,7 @@ zplug::load()
 
         # Branch cmd/src
         case $zspec[as] in
-            bin|cmd)
+            cmd)
                 files=()
                 mkdir -p ${ZPLUG_HOME%/*}/bin 2>/dev/null
 
@@ -327,18 +422,13 @@ zplug::load()
                 typeset -gx -U path
                 ;;
 
-            src|"")
+            src)
                 # Search plugin files by pattern
                 files=($(zsh -c "echo $zspec[dir]/${zspec[of]:-*.sh(N)}" 2>/dev/null))
                 for f in $files
                 do
                     source "$f"
                 done
-                ;;
-
-            debug)
-                # Debug mode
-                # nothing to do
                 ;;
         esac
     done
@@ -347,28 +437,28 @@ zplug::load()
 zplug() {
     local zplug
     zplug="$1"
-    shift # Shift "username/reponame",
 
     # $zplug consists of "username/reponame", specifier:value, ...
     case "$zplug" in
 
         update)
-            zplug::update "$@"
+            shift
+            __zplug::update "$@" ${(k)zplugs}
             return $status
             ;;
 
         list)
-            zplug::list
+            __zplug::list
             return $status
             ;;
 
         i|install)
-            zplug::install ${(k)zplugs}
+            __zplug::install ${(k)zplugs}
             return $status
             ;;
 
         l|load)
-            zplug::load
+            __zplug::load
             return $status
             ;;
 
@@ -377,6 +467,7 @@ zplug() {
             ;;
 
         *)
+            shift # Shift "username/reponame",
             if [[ $zplug =~ ^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+,?$ ]]; then
                 local i specifier
                 for i in "$@"
@@ -399,39 +490,27 @@ zplug() {
                 zplugs+=($zplug "${specifier:-}")
                 # Add dir specifier to $zplugs
                 zplugs[$zplug]+="${zplugs[$zplug]:+,}dir:$ZPLUG_HOME/$zplug"
+
+                # Initialize all specifiers
+                for zplug in ${(k)zplugs}
+                do
+                    zplugs[$zplug]="$(
+                    () {
+                        local -A zspec
+                        local k cnt=0
+                        zspec=( ${(@f)"$(__zplug::parser "$zplug")"} )
+                        for k in ${(k)zspec}
+                        do
+                            printf "$k:$zspec[$k],"
+                        done
+                        echo
+                    } | sed -e 's/,$//'
+                    )"
+                done
             fi
             ;;
     esac
 }
 
-#
-# *************** DEBUG ***************
-#
-
-zplug "k4rthik/git-cal", as:cmd #, do:"echo installed"
-zplug "b4b4r07/zsh-gomi", as:cmd, of:bin/gomi, frozen:1
-zplug "b4b4r07/ssh-keyreg", as:cmd, of:bin
-zplug "b4b4r07/cli-finder", as:cmd, of:bin
-zplug "b4b4r07/tmuxlogger"
-zplug "b4b4r07/enhancd", at:v1
-zplug "hchbaw/opp.zsh", if:"((${ZSH_VERSION//./} < 508))"
-zplug "b4b4r07/http_code", \
-    as:cmd, \
-    of:bin
-zplug "holman/spark", as:cmd
-zplug "junegunn/fzf-bin", \
-    as:bin, \
-    from:gh-r, \
-    file:fzf
-
-# zplug "stedolan/jq" \
-#     as:bin, \
-#     from:gh-r \
-#     | zplug "b4b4r07/emoji-cli"
-
-# zplug list
-# zplug install
-# zplug load
-zplug update --self
-
-export PATH=/bin:/usr/bin:/usr/local/bin
+# __END__ {{{1
+# vim:fdm=marker fdc=3 ft=zsh ts=4 sw=4 sts=4:
